---
label: default
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
pages:
- _posts/test.md
- _posts/2018-11-07-where-are-you-posts.md
- _posts/2018-11-07-making-posts.md
- new-page.md
